import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    // `next-env.d.ts` is generated by the framework and is not ours to fix.
    ignores: ['.next/**', 'node_modules/**', '.pgdata/**', 'next-env.d.ts'],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Feeds, the OpenAPI document, and the Markdown views are plain files
      // rather than routes, so they are linked with <a> on purpose; next/link
      // would attempt a client-side navigation to a non-page.
      '@next/next/no-html-link-for-pages': 'off',
    },
  },
];

export default config;
