import Link from 'next/link';
import { displayDomain, renderMarkdown } from '@/lib/markdown';
import { formatIsoDateTime } from '@/lib/dates';
import type { Item } from '@/lib/types';

/**
 * One item as it appears in a stream.
 *
 * Titles render as real headings at the level the surrounding page dictates
 * (R17) — the reference site uses a `<div>` here, which leaves its item pages
 * with no heading for their own subject.
 *
 * Every part is optional except the body: a riff has no source URL, an
 * unconnected item has no edge badge, and some items have no title at all. All
 * three cases have to degrade cleanly, because all three occur in practice.
 */

interface StreamItemProps {
  item: Item;
  headingLevel?: 2 | 3;
}

export function StreamItem({ item, headingLevel = 3 }: StreamItemProps) {
  const Heading = headingLevel === 2 ? 'h2' : 'h3';

  return (
    <article className="stream-item">
      {item.title ? (
        <Heading className="item-title">
          <Link href={`/i/${item.shortId}`}>{item.title}</Link>
        </Heading>
      ) : null}

      <div
        className="item-body"
        // Content is Markdown authored here or generated by the summariser;
        // renderMarkdown strips embedded HTML before parsing.
        dangerouslySetInnerHTML={{ __html: renderMarkdown(item.content) }}
      />

      <ItemMeta item={item} />
    </article>
  );
}

export function ItemMeta({ item, showPermalink = true }: { item: Item; showPermalink?: boolean }) {
  return (
    <p className="item-meta">
      <span className="item-type">{item.type}</span>

      {item.edgeCount > 0 ? (
        <>
          <span className="item-meta-sep" aria-hidden="true">
            &middot;
          </span>
          {/* R7: the connection count is a visible affordance, and a link
              straight to the connections it counts. */}
          <Link
            className="edge-badge"
            href={`/i/${item.shortId}#connections`}
            title={`${item.edgeCount} connection${item.edgeCount === 1 ? '' : 's'}`}
          >
            {item.edgeCount}
          </Link>
        </>
      ) : null}

      {item.url ? (
        <>
          <span className="item-meta-sep" aria-hidden="true">
            &middot;
          </span>
          <a href={item.url} rel="noopener nofollow ugc">
            {displayDomain(item.url)} &rarr;
          </a>
        </>
      ) : null}

      {showPermalink ? (
        <>
          <span className="item-meta-sep" aria-hidden="true">
            &middot;
          </span>
          <Link href={`/i/${item.shortId}`}>
            {/* R17: a real <time> with a machine-readable datetime. */}
            <time dateTime={formatIsoDateTime(item.publishedAt)}>permalink</time>
          </Link>
        </>
      ) : null}

      {item.tags.length > 0 ? (
        <span className="item-tags">
          {item.tags.map((tag) => (
            <Link key={tag} href={`/search?q=${encodeURIComponent(tag)}`}>
              {tag}
            </Link>
          ))}
        </span>
      ) : null}
    </p>
  );
}
